{
 "title": "Grasshopper | Example Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DB_SOURCE", "label": "DB_SOURCE", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "Custom Trends and Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Custom Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": " $tag_name",
     "query": "SELECT DISTINCT \"response_time\"\nFROM \"locust_requests\"\nWHERE $timeFilter and \"request_type\"='CUSTOM'\nGROUP BY \"name\""
    }
   ]
  },
  {
   "title": "Check success rates",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_check_name",
     "query": "SELECT mean(\"check_passed\") FROM \"locust_checks\" WHERE $timeFilter GROUP BY \"check_name\"\n"
    }
   ]
  },
  {
   "title": "Checks Passed | Total Count",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_check_name",
     "query": "SELECT count(\"check_passed\") FROM \"locust_checks\" WHERE \"check_passed\" = 1 and $timeFilter GROUP BY \"check_name\"\n"
    }
   ]
  },
  {
   "title": "Check failures over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "FAILED: $tag_check_name",
     "query": "SELECT count(\"check_passed\") FROM \"locust_checks\" WHERE (check_passed = 0) and $timeFilter GROUP BY time($__interval), \"check_name\"\n"
    }
   ]
  },
  { "title": "HTTP requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Request Response Times (ms)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_name",
     "query": "SELECT DISTINCT \"response_time\"\nFROM \"locust_requests\"\nWHERE $timeFilter AND (\"success\"='True') AND (\"request_type\"!='custom') AND (\"request_type\"!='CUSTOM')\nGROUP BY  time(1ms), \"name\""
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_exception",
     "query": "SELECT count(\"response_time\")  FROM \"locust_requests\" WHERE $timeFilter\n"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_exception",
     "query": "SELECT count(\"response_time\")  FROM \"locust_requests\" WHERE $timeFilter and \"code\"=~/[45]\\d\\d/\n"
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "user count",
     "query": "SELECT \"user_count\"\nFROM \"locust_requests\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "RPS (Requests per Second)",
   "type": "timeseries",
   "description": "Requests Per Second over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "RPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT c\nFROM (\nSELECT count(response_time) as c \nFROM \"locust_requests\"\nWHERE $timeFilter\nGROUP BY time(1s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP errors over time",
   "type": "graph",
   "description": "Number of requests per second over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"response_time\")\nFROM \"locust_requests\"\nWHERE $timeFilter and \"code\"=~/[45]\\d\\d/\nGROUP BY time($__interval), \"name\", \"code\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "$tag_request_type $tag_name: $tag_exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter and \"code\"=~/[45]\\d\\d/\nGROUP BY \"request_type\", \"name\", \"exception\"\nLIMIT 200",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Locust events and errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Hatching Events",
   "type": "table-old",
   "description": "Hatching Events",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", \"event\", \"node_id\", \"user_count\"\nFROM \"locust_events\" \nWHERE $timeFilter\nAND event <> 'papaya'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Locust Errors",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"exception\")\nFROM \"locust_exceptions\" \nWHERE $timeFilter\nGROUP BY \"exception_tag\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}